# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'BubbleHero' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BubbleHero
  pod 'GameEngine', :git => 'git@github.com:yunpengn/BubbleHeroEngine.git', :branch => 'master'
end
